### ISSUE TITLE
I can't code my message

### ISSUE THREAD

**Issue by mirabos** [QDaves/BBT-Embed#1]
i want to send this but nothing happens
![Снимок](https://user-images.githubusercontent.com/87264667/125192380-3b97d780-e250-11eb-95d5-e846784bcd0c.PNG)

**Comment by QDaves** [comment]
Hey just tried it works for me, are you sure the Plugin was enabled?
If it wont work try out to restart your discord.

Try to copy the example field first and try if it will work, if it doesnt write me again.
Example:
/e title: Your title Here
description: ```Text -1500€
text -100$
text -100$
text -100$
text -100$
text -100$ ```
url: https://discordapp.com
color: #788cd4
timestamp: true
footer_image: https://i.imgur.com/PdBoyGk.png
footer: Footer Text Here
thumbnail: https://i.imgur.com/PdBoyGk.png
image: https://i.imgur.com/PdBoyGk.png
author: Author Name here
author_url: https://discordapp.com
author_icon: https://i.imgur.com/PdBoyGk.png

![image](https://user-images.githubusercontent.com/26190695/125204272-b7a81480-e27c-11eb-8632-beb916db621d.png)

**Comment by QDaves** [comment]
Here a video how to use
https://puu.sh/HVzlo/7ef6478f75.mkv

**Comment by mirabos** [comment]
Thank you very much! Now it works, I don't know how I did that. I'm just copied your example and it worked.

**Comment by QDaves** [comment]
great
